extends SceneTree

var failures := 0
var checks := 0

func _initialize() -> void:
	call_deferred("run")

func expect(condition: bool, name: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		push_error("FAIL: " + name)

func match_for(group := "program") -> MARCCompetition:
	var c := MARCCompetition.new()
	c.configure(group)
	c.prepare()
	c.begin()
	return c

func run() -> void:
	var course := MARCCourse.new()
	expect(course.data.rings.size() == 6, "six rings")
	expect(course.cards(true).size() == 7 and course.cards(false).size() == 6,"group card difference")
	var spawn := course.spawn()
	expect(spawn.origin.distance_to(Vector3(0.4,0.105,-1.6)) < 0.0001,"spawn coordinate")
	expect((-spawn.basis.z).dot(Vector3.RIGHT) > 0.999,"nose faces +x")
	var c := match_for()
	for id in MARCCompetition.NAMES:
		if id == "8": continue
		var rule := c.points_and_limit(id)
		for _i in rule.y: c.award(id)
		var before: int = c.scores[0]
		c.award(id)
		expect(c.scores[0] == before,"score cap " + id)
	# Tunnel bonus is included by the actual A-B-C award sequence.
	if int(c.counts.get("combo",0)) < 2: c.award("combo")
	expect(c.scores[0] == 270,"program task total before landing")
	expect(c.landing_points(Vector3(40,160,10)) == 30,"inner clear landing")
	expect(c.landing_points(Vector3(50,160,10)) == 10,"touching inner line")
	expect(c.landing_points(Vector3(65,160,10)) == 0,"outside landing")
	c = match_for()
	var ring: Dictionary = course.data.rings[0]
	for h in [175.0,160.0,150.0,140.0,125.0]:
		c.tick(0.01,MARCCourse.world(60,280,h),Vector3(0,-0.2,0),true,"white",{})
	expect(c.counts.get("1A",0) == 1,"whole body downward crossing")
	for h in [140.0,150.0,160.0,175.0]:
		c.tick(0.01,MARCCourse.world(60,280,h),Vector3.UP,true,"white",{})
	expect(c.counts.get("1A",0) == 1,"reverse crossing rejected")
	c = match_for()
	for h in [175.0,150.0,125.0]: c.tick(0.01,MARCCourse.world(85,280,h),Vector3.ZERO,true,"white",{})
	expect(not c.counts.has("1A"),"body clipping ring rejected")
	c = match_for()
	for id in ["4A","4B","4C"]: c.award(id)
	expect(c.counts.get("combo",0) == 1,"tunnel consecutive bonus")
	c.award("4A")
	c.award("6")
	c.award("4B")
	c.award("4C")
	expect(c.counts.get("combo",0) == 1,"other scoring task breaks combo")
	c = match_for()
	for _i in 19: c._track_color(0.1,"red",{"id":"7-1","color":"red"})
	expect(not c.cards_locked.has("7-1"),"LED less than two seconds")
	c._track_color(0.1,"red",{"id":"7-1","color":"red"})
	expect(c.cards_locked.get("7-1",false) and c.scores[0] == 15,"LED two seconds scores")
	c._track_color(2.0,"yellow",{"id":"7-2","color":"green"})
	c._track_color(2.0,"green",{"id":"7-2","color":"green"})
	expect(c.cards_locked.has("7-2") and not c.cards_locked["7-2"],"first wrong locks card")
	var remaining := c.remaining
	c.reset_flight()
	expect(c.scores[0] == 15 and c.cards_locked.has("7-2") and c.remaining == remaining,"reset retains scores locks and timer")
	c = match_for("hybrid")
	c.attempt("3")
	c.award("3")
	c.attempt("2")
	expect(not c.award("2"),"skipped task cannot score")
	c.attempt("6")
	c.attempt("6")
	expect(c.scores[0] == -20,"wrong stage once per prop")
	expect(not c.reset_allowed() and c.can_manual() and not c.can_program(),"hybrid manual phase gate")
	c.end_first_stage()
	c.tick(30,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	expect(c.stage == 1 and c.remaining == 150 and c.can_program() and not c.can_manual(),"phase timing and input gate")
	c = match_for()
	for i in 361:
		var angle := TAU * i / 360.0
		c._track_pole(Vector3(260 + cos(angle)*24,280 + sin(angle)*24,70),10)
	expect(c.counts.get("2",0) == 1,"counterclockwise full pole orbit")
	c = match_for()
	for i in 361:
		var angle := -TAU * i / 360.0
		c._track_pole(Vector3(260 + cos(angle)*24,280 + sin(angle)*24,70),10)
	expect(not c.counts.has("2"),"clockwise pole orbit rejected")
	c = match_for()
	c._track_bridge(Vector3(360,180,60),Vector3(360,140,60),10)
	c._track_bridge(Vector3(360,140,130),Vector3(360,180,130),10)
	expect(c.counts.get("3",0) == 1,"bridge under then over")
	c = match_for()
	c._track_bridge(Vector3(360,140,130),Vector3(360,180,130),10)
	expect(not c.counts.has("3"),"bridge reverse sequence rejected")
	c = match_for()
	c.referee("intervention")
	expect(not c.award("6"),"intervention suppresses scores")
	c.reset_flight()
	expect(c.award("6"),"reset restores scoring")
	c = match_for()
	c._track_bridge(Vector3(360,180,60),Vector3(360,159,60),10)
	c._track_bridge(Vector3(360,159,60),Vector3(360,159,130),10)
	c._track_bridge(Vector3(360,159,130),Vector3(360,180,130),10)
	expect(not c.counts.has("3"),"partial-body underpass cannot complete bridge")
	c = match_for()
	for _i in 15: c._track_color(0.1,"red",{"id":"7-1","color":"red"})
	c._track_color(0.1,"white",{"id":"7-1","color":"red"})
	for _i in 10: c._track_color(0.1,"red",{"id":"7-1","color":"red"})
	expect(not c.cards_locked.has("7-1"),"LED continuity breaks on white")
	c._track_color(0.1,"red",{})
	for _i in 10: c._track_color(0.1,"red",{"id":"7-1","color":"red"})
	expect(not c.cards_locked.has("7-1"),"leaving card breaks continuity")
	c = match_for()
	for _i in 100: c.tick(0.01,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	expect(c.last_landing == -1,"no return credit without flying")
	c.tick(0.1,MARCCourse.world(40,160,60),Vector3.UP,true,"white",{})
	for _i in 100: c.tick(0.01,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	expect(c.last_landing == 30,"stationary return provisional points")
	c.tick(0.1,MARCCourse.world(40,160,60),Vector3.UP,true,"white",{})
	expect(c.last_landing == -1,"reflight revokes provisional landing")
	c = match_for()
	c.remaining = 0.005
	c.tick(0.01,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	expect(c.state == "finished" and not c.award("6"),"no scores after timeout")
	c = match_for("hybrid")
	for id in MARCCompetition.ORDER:
		c.attempt(id)
		c.award(id)
	expect(c.scores[0] == 100,"hybrid manual phase maximum")
	c.end_first_stage()
	c.tick(30,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	c.award("6")
	for id in ["7-1","7-2","7-3","7-4","7-5","7-6"]: c.award(id)
	c.last_landing = 30
	c.finish()
	expect(c.scores[0] + c.scores[1] == 200,"hybrid total maximum")
	c = match_for("hybrid")
	c.award("1A")
	c.end_first_stage()
	c.tick(30,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	c.award("6")
	c.referee("manual_violation")
	expect(c.zero_stage_two and not c.major_zero and c.scores[0] == 20,"hybrid violation preserves first stage")
	c = match_for()
	c.award("takeoff")
	c.referee("manual_violation")
	expect(c.major_zero and c.state == "finished","program manual violation zeroes whole match")
	c = match_for("hybrid")
	c.tick(0.1,MARCCourse.world(40,160,60),Vector3.UP,true,"white",{})
	c.tick(0.1,MARCCourse.world(40,160,10),Vector3.ZERO,false,"white",{})
	expect(c.scores[0] == 0,"normal pad landing does not incur ground penalty")
	c = match_for("hybrid")
	c.tick(0.1,MARCCourse.world(100,160,60),Vector3.UP,true,"white",{})
	c.tick(0.1,MARCCourse.world(100,160,10),Vector3.ZERO,false,"white",{})
	expect(c.scores[0] == -10,"off-pad ground contact penalty")
	var scene := MARCArena.new()
	root.add_child(scene)
	scene.set_card("7-1","green")
	expect(scene.sensor_at(MARCCourse.world(220,220,40)).color == "green","sensor at bottom 30cm")
	expect(scene.sensor_at(MARCCourse.world(220,220,40.1)).color == "none","sensor above bottom 30cm")
	expect(scene.sensor_at(MARCCourse.world(241,220,30)).color == "none","sensor outside card")
	scene.queue_free()
	await process_frame
	print("MARC_LOGIC_TESTS checks=%d failures=%d" % [checks,failures])
	quit(1 if failures else 0)
